### ISSUE TITLE
mod not working with 13 update

### ISSUE THREAD

**Issue by JAZ71** [xforce/anno1800-mod-loader#115]
just updated to v13 and mods wont work

**Comment by theotherp** [comment]
I knew I shouldn't've updated :-(

**Comment by Ekyu** [comment]
I did a dumb dumb at updated my game too... hoping for a quick fix !

**Comment by Rickardoko** [comment]
I have the same problem... 
I can't start Anno 1800 via Steam / Uplay after game update 13. 
I can’t start Anno 1800 because i got his warning! “Anno 1800 mod loader this version is nog compatible with your current game.”

I have Anno mod loader version v0.8.2. 

I see that I don’t have VCRedist installed. 
My first question is in wich folder I must install VCRedist? 

My second question is what to do to solve this problem?
A few months ago I had te same problem with the Anno mod loader what makes that there was nog way to play Anno 1800. With lot’s of frustrations I deleted all my mods and the whole game from my computer and installed it again. I don’t want to make the same desision again. 
I don’t get why it’s so difficult to use the mod loader….

**Comment by idbureau** [comment]
@Rickardoko 
Just wait patiently... This is a matter of replacing 1 single file (python35.dll). After this file is updated, you can copy/paste the new version, and the game can be played as usual. No need for reinstall, or removing mods.

**Comment by MisterMedion** [comment]
How and where can I see when the modloader is updated and compatible with the new gameupdate V13? unfortunately I also aktkualisiert my game and now the game no longer recognizes the mods.

**Comment by idbureau** [comment]
You can Subscribe to this thread... There will be someone messaging for sure... :)

**Comment by MisterMedion** [comment]
has anyone experience how long it takes until a new version is there and you can play the game again with mods

**Comment by coder-guy** [comment]
He _might_ be working on it right now, in fact, as there was a commit to the master branch just 20 minutes ago.  I imagine we won't have to wait too long.

**Comment by xforce** [comment]
This is now fixed in 0.8.3. See https://github.com/xforce/anno1800-mod-loader/releases/tag/v0.8.3

**Comment by ssgh-man** [comment]
Hello, i hope someone can help me. I downloaded and replaced the two new files for version 13. however, my savegames only work without mods. When i start a new game the mods are loaded... I would not like to start a new game. Can someone help me with this problem please?

**Comment by idbureau** [comment]
> This is now fixed in 0.8.3. See https://github.com/xforce/anno1800-mod-loader/releases/tag/v0.8.3

Many Thanks...
Do you have a donate button (Paypal??)

**Comment by Rickardoko** [comment]
Thank you for solving this. The game and the mods are working fine now.

**Comment by ssgh-man** [comment]
Something I have to do wrong ... I downloaded the new files from version 0.8.3 and replaced both dll files. but the mods still don't load with my old savegames. I use the mods from "Spice it up". I have already removed them from the mod folder and downloaded them again ... that didn't help either. I'm slowly desperate.

**Comment by EclipseTriant** [comment]
Hi. I play on Russian. After 13 update, i downloaded new files and replace both dlls, but my game still say me: This version not compatible with your current Game Version, but my game version: 13.0.1064331 and both dlls from 15.12

Dont know what to do.

**Comment by xforce** [comment]
Update notification for anyone on 0.8.2 is now enabled.

**Comment by fawasaljabri** [comment]
I have Anno 1800 version 12.1.1036020 and modloader version 0.8.3 
and still not warking it says to me: This version not compatible with your current Game Version

![WhatsApp Image 2021-12-19 at 22 09 30](https://user-images.githubusercontent.com/26743743/146680076-672d403d-6864-4c02-b820-97698c3ef807.jpeg)
![WhatsApp Image 2021-12-19 at 22 09 29 (1)](https://user-images.githubusercontent.com/26743743/146680078-4d50aa57-5a40-4517-a377-555e687bffc2.jpeg)
![WhatsApp Image 2021-12-19 at 22 09 29](https://user-images.githubusercontent.com/26743743/146680079-ea2c0408-ffb7-46d7-9665-d151e5b64ae3.jpeg)

**Comment by xforce** [comment]
> I have Anno 1800 version 12.1.1036020 and modloader version 0.8.3 and still not warking it says to me: This version not compatible with your current Game Version
> 
> ![WhatsApp Image 2021-12-19 at 22 09 30](https://user-images.githubusercontent.com/26743743/146680076-672d403d-6864-4c02-b820-97698c3ef807.jpeg) ![WhatsApp Image 2021-12-19 at 22 09 29 (1)](https://user-images.githubusercontent.com/26743743/146680078-4d50aa57-5a40-4517-a377-555e687bffc2.jpeg) ![WhatsApp Image 2021-12-19 at 22 09 29](https://user-images.githubusercontent.com/26743743/146680079-ea2c0408-ffb7-46d7-9665-d151e5b64ae3.jpeg)

Correct. as the release specifies. 0.8.3 requires GU 13.

**Comment by fawasaljabri** [comment]
> > I have Anno 1800 version 12.1.1036020 and modloader version 0.8.3 and still not warking it says to me: This version not compatible with your current Game Version
> 
> Correct. as the release specifies. 0.8.3 requires GU 13.

Ok then how can I update the game to version 13…??
I have the game in epic games but it seems that I can’t find the way to update anno 1800 to version 13..

any suggestions that might help me..please..?

**Comment by mhhawwach** [comment]
hello there,

im having an issue where the mod is working but changes are not applied Ingame , also i cannot see modding detected note.

however , if i go into the mods folder , i can see the game created the ".cache" folder for the mods in the directory.

my game is v13 and the mod loader version is 0.8.3 . i installed verdist and all .

any one can help ?
